//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cl.Tienda.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ropa
    {
        public int iId { get; set; }
        public string vNombre { get; set; }
        public Nullable<int> iGenero { get; set; }
        public string vCategoria { get; set; }
        public Nullable<decimal> dValor { get; set; }
        public Nullable<bool> bDisponible { get; set; }
    }
}
